### ISSUE TITLE
Show list of directions

### ISSUE THREAD

**Issue by slinlee** [cogsci/wigglemap#14]
Show the directions in a list somewhere.

**Comment by andrewdanks** [comment]
This is a great idea. Maybe this should be in some inspector-like semi-transparent popover window, that can be opened by a button/icon somewhere, so we don't display so much information at once in the UI

**Comment by epan** [comment]
Have the button "List" under the map open a new window to show directions of the current route. 

See wireframe: http://cl.ly/image/3L3p3E0u021L

**Comment by dhchow** [comment]
Testing images

![Test image](http://cl.ly/image/3L3p3E0u021L/Screen%20Shot%202012-10-24%20at%209.37.01%20PM.png)

**Comment by dhchow** [comment]
Done! No elevation just yet though. That summary data doesn't seem to be readily available.

**Comment by epan** [comment]
I think Andrew did some code for elevation but I'm not 100% sure it works
or where it is.

**Comment by andrewdanks** [comment]
It works.

I just added the "ft climb" metric to the route info. However, this won't be shown right away because calculating the total climb requires a service call; so it'll show 0 initially, and show the correct value a few seconds later.

Also, I'm not sure if we want to show min(0, total climb)  or allow negatives. For now, I allowed negatives.

**Comment by epan** [comment]
Does this return the climb - descent or does it sum up all the climbs?
Negative is fine.

On Thu, Oct 25, 2012 at 2:05 AM, Andrew Danks notifications@github.comwrote:

> It works.
> 
> I just added the "ft climb" metric to the route info. However, this won't
> be shown right away because calculating the total climb requires a service
> call; so it'll show 0 initially, and show the correct value a few seconds
> later.
> 
> Also, I'm not sure if we want to show min(0, total climb) or allow
> negatives. For now, I allowed negatives.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/andrewdanks/reroute/issues/14#issuecomment-9770622.

## 

Eric

**Comment by andrewdanks** [comment]
The service call returns a list of numbers representing the change in elevations for each segment in the route, since we were going to integrate this with the timeline somehow, so I just summed up the deltas, which is the overall change in elevation, right?

Although, if we're just taking the difference in elevation between the start and end points, it'll be more efficient just to calculate just those two.

But, I think it'll be interesting to somehow incorporate the list of elevations in the future, since a rider can choose routes that have a more gradual change in elevation than others.

**Comment by dhchow** [comment]
Yeah summing up the deltas gives overall change in elevation. Though I
wonder what's more useful for this situation, overall change or max
change/delta? A steep hill in the middle of the route that brings me back
to my original elevation is still a tough ride.

Definitely would be helpful to mark at least the greatest delta point of
the route, on the timeline, or on the map (if not all of the data points).
I'll look into this later when I'm back home.

**Comment by slinlee** [comment]
grade % is more descriptive than elevation gain, and creating our own scale/rating is even better. I still don't know if 200ft gain is strenuous or not.

**Comment by dhchow** [comment]
Yeah, having our own scale/rating is a good idea. I (as a non-biker) have
no idea what #'s of ft gain really mean.

Created a new issue for this (for later, outside of milestone):
https://github.com/andrewdanks/reroute/issues/35

**Comment by andrewdanks** [comment]
Hmm, this is a really good point. Numbers don't always mean much.

I wonder if the grade should be based on a average of the ∆elevation/∆distance over all the segments in the route?

But then we also have the issue of determining what's "high" and what's "low"

**Comment by slinlee** [comment]
I'll find a rating scale. I remember reading how each % increase made a pretty big difference in how many people were willing to ride

**Comment by andrewdanks** [comment]
Wow, if you could find it, that'd be awesome!
