### ISSUE TITLE
redirect www.wigglemap.com to wigglemap.com

### ISSUE THREAD

**Issue by slinlee** [cogsci/wigglemap#68]
This is still SEO best practice right?

**Comment by andrewdanks** [comment]
I don't think it matters... At least this site doesn't think so http://seoroi.com/seo-faq/www-vs-non-www-seo-faq/

**Comment by slinlee** [comment]
That link says it matters in a particular case. Anyway, lets use a 301 permanent redirect to go to wigglemap.com

**Comment by epan** [comment]
It says it matters only that you should'nt have it be possible to see
www.wigglemap.com AND wigglemap.com because spiders will see it as
duplicate content and you will SEO compete with yourself.

will this be important for stuff like google analytics etc where we need to
exclude the www. from goals etc?

On Wed, Oct 31, 2012 at 10:39 AM, slinlee notifications@github.com wrote:

> That link says it matters in a particular case. Anyway, lets use a 301
> permanent redirect to go to wigglemap.com
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/cogsci/wigglemap/issues/68#issuecomment-9954403.

## 

Eric

**Comment by epan** [comment]
So right now we let people go to http://www.wigglemap.com OR http://wigglemap.com depending on what they type. THIS IS THE ONE EXCEPTION where it is NOT ok for SEO. So let's set up the 301 redirect to aways go to http://wigglemap.com whether they type the www or not.

**Comment by kmiyashiro** [comment]
www makes us look old and out of touch anyway.
